name: VoltskiyaUtilities
version: 1.0
main: voltskiya.apple.utilities.UtilitiesPlugin
api-version: 1.19
authors: [ appleptr16 ]
softdepend: [ LoadDependencies, AppleConfigs, AppleMCUtil, DecodingNms ]
